Admin wasa changes
PSMRI/ADMIN-UI pull request #52
Opened 2024-11-30 07:33 UTC by NKOKKILIGADDA87

## 📋 Description

JIRA ID: 

Please provide a summary of the change and the motivation behind it. Include relevant context and details.

---

## ✅ Type of Change

- [ ] 🐞 **Bug fix** (non-breaking change which resolves an issue)
- [ ] ✨ **New feature** (non-breaking change which adds functionality)
- [ ] 🔥 **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🛠 **Refactor** (change that is neither a fix nor a new feature)
- [ ] ⚙️ **Config change** (configuration file or build script updates)
- [ ] 📚 **Documentation** (updates to docs or readme)
- [ ] 🧪 **Tests** (adding new or updating existing tests)
- [ ] 🎨 **UI/UX** (changes that affect the user interface)
- [ ] 🚀 **Performance** (improves performance)
- [ ] 🧹 **Chore** (miscellaneous changes that don't modify src or test files)

---

## ℹ️ Additional Information

Please describe how the changes were tested, and include any relevant screenshots, logs, or other information that provides additional context.

2024-11-30 07:58 UTC, sandipkarmakar3 commented
@coderabbitai review

2024-11-30 08:04 UTC, sandipkarmakar3 commented
All changes I have reviewed.
Everything is as per the requirement.
We used sessionstorage.service to store the data to session storage.
We removed all localstorage code and used session storage.
We used jwt token for validate user's session.

2025-01-23 08:53 UTC, sandipkarmakar3 reviewed
All changes I have reviewed.
Everything is as per the requirement.
We used sessionstorage.service to store the data to session storage.
We removed all localstorage code and used session storage.
We used jwt token for validate user's session.

2025-01-31 10:44 UTC, devikasuresh20 requested changes

2025-01-31 10:44 UTC, devikasuresh20 commented on src/app/app-provider-admin/provider-admin/activities/add-fields-to-project/add-fields-to-project.component.ts
> +        'Field Name already exixts in the Project, Kindly give different name',
@sandipkarmakar3 "exists" - please correct the spelling

2025-01-31 10:44 UTC, devikasuresh20 commented on src/app/app-provider-admin/provider-admin/activities/parking-place-master/parking-place-master.component.html
> +      <mat-icon mdSuffix>search</mat-icon>
@sandipkarmakar3  Pls use matSuffix instead of mdSuffix

2025-01-31 11:10 UTC, sandipkarmakar3 commented on src/app/app-provider-admin/provider-admin/activities/parking-place-master/parking-place-master.component.html
> +      <mat-icon mdSuffix>search</mat-icon>
done

2025-01-31 11:10 UTC, sandipkarmakar3 commented on src/app/app-provider-admin/provider-admin/activities/add-fields-to-project/add-fields-to-project.component.ts
> +        'Field Name already exixts in the Project, Kindly give different name',
done

2025-01-31 11:19 UTC, merged